services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend_dev
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/artmapdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&connectTimeout=10000&autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: RootPass123#
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./backend/src:/app/src
      - /root/.m2:/root/.m2
    networks:
      - app-network
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql:8
    container_name: db_dev
    environment:
      MYSQL_ROOT_PASSWORD: RootPass123#
      MYSQL_DATABASE: artmapdb
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
