# Etapa de build
FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app

COPY pom.xml /app/pom.xml
RUN mvn dependency:go-offline -B

COPY src /app/src
RUN mvn clean package -DskipTests  # Construiește aplicația fără a rula testele

# Etapa finală (runtime)
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/Artmap-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080
CMD ["java", "-jar", "app.jar"]
